# Generated by Django 4.2 on 2025-03-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='core.category')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='sub_categories',
            field=models.ManyToManyField(related_name='services', to='core.subcategory'),
        ),
    ]
